"""
SmartDoc Prompts Module  
Templates y prompts para agentes ReAct
"""

from .react_templates import (
    ReactTemplates,
    SMARTDOC_SYSTEM_PROMPT,
    REACT_MAIN_TEMPLATE,
    ACADEMIC_RESEARCH_TEMPLATE,
    BUSINESS_RESEARCH_TEMPLATE,
    TECHNICAL_RESEARCH_TEMPLATE,
    SYNTHESIS_TEMPLATE,
    DEFAULT_PROMPT_CONFIGS,
    EXAMPLE_INPUTS
)

__all__ = [
    "ReactTemplates",
    "SMARTDOC_SYSTEM_PROMPT", 
    "REACT_MAIN_TEMPLATE",
    "ACADEMIC_RESEARCH_TEMPLATE",
    "BUSINESS_RESEARCH_TEMPLATE", 
    "TECHNICAL_RESEARCH_TEMPLATE",
    "SYNTHESIS_TEMPLATE",
    "DEFAULT_PROMPT_CONFIGS",
    "EXAMPLE_INPUTS"
]
